backbone:
  name: EfficientRep
  pretrained:
  params:
    channels_list: [64, 128, 256, 512, 1024]
    num_repeats: [1, 6, 12, 18, 6]
    depth_mul: 0.33
    width_mul: 0.25

neck:
  name: RepPANNeck
  params:
    channels_list: [256, 128, 128, 256, 256, 512]
    num_repeats: [12, 12, 12, 12]
    depth_mul: 0.33
    width_mul: 0.25

heads:
  - name: YoloV6Head
    params:
      n_classes: null
      n_layers: 3
      reg_max: 0
    loss: 
      name: YoloV6Loss
      params:
        iou_type: siou